Add Bar Chart to  AboutMe.html, Add data to drawChar in script.js
NzingaHolloman/my-portfolio pull request #12
Opened 2020-03-08 00:33 UTC by NzingaHolloman

2020-03-08 05:13 UTC, josueetcom approved these changes
Just some style changes but otherwise LGTM! 🎉

2020-03-08 05:13 UTC, josueetcom commented on portfolio/src/main/webapp/script.js
> +        ['Destination', 'Votes',],
Is the `,` before `]` supposed to be there?

2020-03-08 05:13 UTC, josueetcom commented on portfolio/src/main/webapp/script.js
> +        ['Philadelphia', 9]
[Style](https://google.github.io/styleguide/jsguide.html#features-arrays-trailing-comma): Include a trailing comma whenever there is a line break between the final element and the closing bracket.

```suggestion
        ['Philadelphia', 9],
```

This makes it easier to add more items without this particular line appearing changed.

2020-03-08 05:13 UTC, josueetcom commented on portfolio/src/main/webapp/script.js
> +        }
[Style](https://google.github.io/styleguide/jsguide.html#features-objects-use-trailing-comma): Include a trailing comma whenever there is a line break between the final property and the closing brace.

```suggestion
        },
```

For the same reason as above 😃

2020-03-08 05:26 UTC, josueetcom requested changes
Changing to **Request changes** to make sure comments from PR #11 are addressed either there or here 😄

2020-03-09 04:55 UTC, TengkuHanaShafikah commented
Other than Josue's comments above, everything looks good to me!

2020-03-09 04:55 UTC, TengkuHanaShafikah reviewed
Other than Josue's comments above, everything looks good to me! Nice job!

2020-04-01 02:48 UTC, merged